title: De bron van het kwaad.nl
email: bron@hetkwaad.nl
description: >- # this means to ignore newlines until "baseurl:"
  Hetkwaad.nl is the ultimate destination for all things dark and sinister. This site is run by a programmer turned pentester turned YouTuber who delves into the world of horror games with a passion. From the latest game releases to in-depth analysis of classic titles, Hetkwaad.nl offers a unique perspective on the genre that will keep you on the edge of your seat. Whether you're a seasoned horror fan or just looking to explore the world of fear, Hetkwaad.nl is the perfect place to start. With a focus on both gameplay and atmosphere, this site will take you on a journey through the darkest corners of gaming and beyond. So prepare yourself for a thrilling ride and enter the realm of Hetkwaad.nl - the source of evil.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hetkwaad.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 4a6f62
github_username:  4a6f62

# Build settings
permalink: pretty
date_format: "%b %-d, %Y"
