# name: Update Posts

# on:
#   schedule:
#     - cron:  '0 2 * * *'
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Install dependencies
#       run: pip install requests
#     - name: Run script
#       run: python yt.py        

#     - name: Commit to the repo
#       run: |
#           git config --global user.name '4a6f62'
#           git config --global user.email '4a6f62@users.noreply.github.com'
#           git add .
#           git commit -am "Update post list"
#           git push
