name: Update Posts

#### Thing to notice 1 ####
on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run script to get videos from youtube
        #### Thing to notice 2 ####
        run: |
          ./scripts/post_files_from_GET_json.sh

      - name: Commit to the repo
        run: |
          git config --global user.name '4a6f62'
          git config --global user.email '4a6f62@users.noreply.github.com'
          git add .
          git commit -am "Update post list"
          git push
